version: "3"

services:
  backend:
    container_name: "uaasb_backend"
    build: .
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "${PORT}:${PORT}"
    env_file: ".env"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  postgres:
    container_name: "uaasb_postgres"
    image: "postgres:13.6-alpine"
    ports:
      - "${PGPORT}:${PGPORT}"
    env_file: ".env"

  redis:
    container_name: "uaasb_redis"
    image: 'redis:6.0-alpine'
    ports:
      - '6379:6379'

volumes:
  data_backend_libs:
    driver: local
