sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=tests

sonar.inclusions=src/**/*.ts
sonar.test.inclusions=tests/**/*.spec.ts

sonar.exclusions=coverage/**,dist/**,node_modules/**,src/**/*.d.ts,src/assets/**,src/locales/**,src/tensor/temp/**,src/tensor/swindlers-temp/**,src/shared/video/temp/**
sonar.coverage.exclusions=tests/**,src/**/*.d.ts,src/**/_mocks/**,src/testing/**,src/vitest-setup.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
