export const LOGS_CHAT_THREAD_IDS = {
  PORN: 36,
  SWINDLERS: 37,
  ANTI_RUSSIAN: 38,
  STRATEGIC: 39, // WARN! Use only for errors, not for messages
  CARDS: 40,
  URLS: 41,
  LOCATIONS: 42,
  MENTIONS: 43,
  COUNTEROFFENSIVE: 44,
  OBSCENE: 45,
  ANTISEMITISM: 46,
  STATISTICS: 138,
  CHANNEL_MESSAGES: 384_547,
};

export const SECOND_LOGS_CHAT_THREAD_IDS = {
  SWINDLERS: 10,
};
