export const GOOGLE_SHEETS_NAMES = {
  UKRAINIAN_PHRASES: 'Ukrainian_phrases',
  SWINDLERS: 'SWINDLERS',
  COUNTER_OFFENSIVE: 'Counter_offensive',
  NSFW: 'NSFW',
  STRATEGIC_NEGATIVE: 'NEGATIVE',
  STRATEGIC_POSITIVE: 'POSITIVE',
  STATISTICS: 'STATISTICS',
};
