#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "\033[0;33m"
echo "***************************************************"
echo ""
echo "We use validate-branch-name."
echo "To push a branch, be sure you have right prefix, ticket name in uppercase, and description split by underscore. Example branch name:"
echo ""
echo "  * feature/UABOT-8_create_ui_elements"
echo "  * hotfix/UABOT_add_missing_routes"
echo ""
echo "Read more: https://github.com/JsonMa/validate-branch-name"
echo ""
echo "***************************************************"
echo "\033[0m"

echo "\033[0;33m"
echo "***************************************************"
echo ""
echo "Lint time can be long for the first time."
echo ""
echo "***************************************************"
echo "\033[0m"

npx validate-branch-name
npm run lint
