name: Lint Code

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'


jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Lint JS
        run: npm run lint:js

      - name: Run Lint TS
        run: npm run lint:type-check
